project:
  type: website
  output-dir: docs

website:
  site-url: "https://nilswiersma.github.io/"
  title: "singlebitupset"
  sidebar:
    style: docked
    search: true
    background: dark
    collapse-level: 3
    contents:
      - index.qmd
      - section: "Posts"
        contents:
          - section: "2023"
            contents:
              - 2023/hexacon23/index.qmd
          - section: "2024"
            contents:
              - 2024/sergei23/index.qmd
      - about.qmd

format:
  html:
    theme: 
      - darkly
      - custom.scss
    css: styles.css
    toc: true



